# Generated by Django 4.2.17 on 2024-12-13 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0002_productsnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsnapshot',
            name='batch_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
